//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : WordDict
//  @ File Name : EErrorCode.hpp
//  @ Date : 2015/2/10
//  @ Author : wangqunfeng
//
//


#if !defined(_EERRORCODE_H)
#define _EERRORCODE_H

/** \brief 错误码枚举类型
 *
 * \param
 * \param
 * \return
 *
 */

enum EErrorCode
{
    E_SUCCESS,

    E_ISERR,
    E_OSERR,

    E_WORDERR,
    E_EXPERR,

    E_EPERR,
    E_SKERR,
    E_PPERR,
    E_USRERR,
    E_MEMERR,
    E_PARAERR,

    E_ERR,
};

/** \brief 错误码转换函数
 * 将错误码转换为用户可读的提示信息
 * \param err EErrorCode
 * \return const char*
 *
 */
const char *err2str(EErrorCode err);

#endif  //_EERRORCODE_H
